### ISSUE TITLE
AgoraRtcEngine_iOS version 3.2.1 - Symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by ThuanNgo-Belive** [AgoraIO-Community/Agora-iOS-Swift-Example#1]
Hi everyone. 
I got a new issue when I upgraded AgoraRtcEngine_iOS to the latest version 3.2.1. 
Xcode 12 can't build. Here's the log : 

```
Undefined symbols for architecture arm64:
  "_registerVideoPreProcessor", referenced from:
      AgoraYuvPreProcessor::~AgoraYuvPreProcessor() in videoprp(AgoraYuvPreProcessor.o)
      AgoraYuvPreProcessor::RegisterToEngine(AgoraYuvPreProcessor*) in videoprp(AgoraYuvPreProcessor.o)
  "_registerVideoSource", referenced from:
      -[AgoraVideoSource Detach] in videoprp(AgoraVideoSourceObjc.o)
  "_registerVideoSourceEx", referenced from:
      -[AgoraVideoSource Attach] in videoprp(AgoraVideoSourceObjc.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
If I downgrade to version 3.1.0, it works fine.  I've tried with many steps as "pod deintegrate", clear, delete Xcode data but It still not work :( 
Anyone can help me to check it? Thank you very much....

**Comment by maxxfrazer** [comment]
I just tried it and it looks to build fine with Xcode 12.3, and run without issues on iPadOS 14.2.
Here's the Podfile.lock after updating Podfile and running pod update:
```ruby
PODS:
  - AgoraRtcEngine_iOS (3.2.1)

DEPENDENCIES:
  - AgoraRtcEngine_iOS (~> 3.2.0)

SPEC REPOS:
  trunk:
    - AgoraRtcEngine_iOS

SPEC CHECKSUMS:
  AgoraRtcEngine_iOS: bf8ee53108d31dd9e3b7e448701b9098162c42c7

PODFILE CHECKSUM: 8e236747889820ca83025fe448107ab56d75eec9

COCOAPODS: 1.10.0
```

The only error I get is that `setLocalVoiceChanger` is now deprecated - I'll update that in the repo soon.

**Comment by maxxfrazer** [comment]
I'm going to close the ticket, cannot reproduce and no response from @ThuanNgo-Belive
Please re-open if there's any more information.
